config/routes.rb
WdiShoppingMongo::Application.routes.draw do
  resources :items

end

app/models/item.rb
class Item
  include Mongoid::Document
  field :name, type: String
  field :quantity, type: Integer
  field :is_completed, type: Mongoid::Boolean
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
	def index
    @items = Item.all
    if params[:stuff] == "true"
      @stuff = params [:stuff]
    end
  end

  def show
  end

  def new
    @item = Item.new
  end

  def edit
  	@item = Item.find(params[:id])
  end

  def create
	  @item = Item.new(item_params)

    if @item.save
			redirect_to items_path, notice: 'Item was successfully created.'
    else
      render action: 'new'
    end
  end

  def update
  	@item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to items_path, notice: 'Item was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
	 	@item = Item.find(params[:id])
    @item.destroy
		redirect_to items_url
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:name, :quantity, :is_completed)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/edit.html.erb
<h1>Edit item :)</h1>
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br>
    <%= f.number_field :quantity %>
  </div>
  <div class="field">
    <%= f.label "Completed?" %><br>
    <%= f.check_box :is_completed %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/index.html.erb
<h1>My Shopping List</h1>

<h2><%= @stuff %></h2>

<table>
<!--   <thead>
    <tr>
      <th>Name</th>
      <th>(Quantity)</th>
      <th>Completed?</th>
      <th>Actions</th>

    </tr>
  </thead> -->

  	<ul class='list'>
    	<% @items.each do |item| %>
      	<li>
        <%= item.name %>
        (<%= item.quantity %>)
        <%= item.is_completed %>
        <span class="links">
        	<%= link_to 'Edit', edit_item_path(item) %>
        	<%= link_to 'Delete', item, method: :delete, data: { confirm: 'Are you sure?' } %>
      	</span>
    <% end %>
</table>

<br>

<%= link_to 'New Item', new_item_path, class: "button" %>

app/views/items/new.html.erb
<h1>Add an item to the shopping list!</h1>
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br>
    <%= f.number_field :quantity %>
  </div>
  <div class="field">
    <%= f.label "Completed?" %><br>
    <%= f.check_box :is_completed %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WdiShoppingMongo</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="lines"></div>

	<%= yield %>

<br /><br />
<hr />
Params: <%= params %>
</body>
</html>